In [ ]:
import numpy as np
array = np.zeros([2,2])
print("array initialized with zeros", array)

array initialized with zeros [[0. 0.]
 [0. 0.]]


In [ ]:
import numpy as np
ones_array = np.ones([4,2], dtype = int)
print("all one array", ones_array)

all one array [[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [ ]:
import numpy as np
array = np.full((3,3),9)
print("array filled with 9", array)


array filled with 9 [[9 9 9]
 [9 9 9]
 [9 9 9]]


In [ ]:
import numpy as np
array = np.full((4,2),9 , dtype= int)
print("int array filled with 9" , array)


int array filled with 9 [[9 9]
 [9 9]
 [9 9]
 [9 9]]


In [ ]:
import numpy as np
a = np.array ([[1.9, 2.3],[3.7 , 4.6]])
zeros_array = np.zeros_like(a, dtype = int)
print("Original array", a)
print("zeros array with int",zeros_array)

Original array [[1.5 2.5]
 [3.5 4.5]]
zeros array with int [[0 0]
 [0 0]]


In [ ]:
import numpy as np
a = np.array([[1.4,3.5], [5.5 , 5.9]])
ones_array = np.ones_like(a , dtype = int)
print("original array", a)
print("ones array with int ", ones_array)


original array [[1.4 3.5]
 [5.5 5.9]]
ones array with int  [[1 1]
 [1 1]]


In [ ]:
from types import new_class
import numpy as np
new_list= [1,2,3,4]
array = np.array ( new_list)
print("original list", new_list)
print ("converted numpy array" , array)


original list [1, 2, 3, 4]
converted numpy array [1 2 3 4]


In [ ]:
import numpy as np
array = np.arange(10,50)
print("array with values of 10 to 50", array)



array with values of 10 to 50 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
import numpy as np
array_eye = np.eye(3,3)
print("3 * 3 matrix" , array_eye)

3 * 3 matrix [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
random_array = np.random.random(30)
value = random_array.mean()
print("random array", random_array)
print("mean value", value)

random array [0.69065426 0.71654179 0.86635321 0.35344033 0.80272064 0.30467493
 0.18167698 0.4412025  0.12944139 0.88185953 0.15492025 0.71087759
 0.32101342 0.99372648 0.50431731 0.55912459 0.15174125 0.93427204
 0.24263885 0.72903659 0.15004263 0.33929171 0.40447415 0.96026543
 0.20801469 0.31465843 0.65230306 0.54679868 0.33857431 0.62094344]
mean value 0.5068533481458496


In [ ]:
import numpy as np
random_array = np.random.random(100)
size = (10, 10)
print(random_array)
min_value = np.min(random_array)
max_value = np.max(random_array)
print("minimum value", min_value)
print("maximum value", max_value)





[0.33259288 0.31457404 0.42487926 0.12374193 0.52747962 0.62774247
 0.04924177 0.50678927 0.4149303  0.59342724 0.16846125 0.23383117
 0.96168487 0.82797337 0.14253574 0.63636818 0.88712823 0.42007776
 0.46391606 0.57303128 0.28505598 0.52646617 0.58665002 0.49583568
 0.08277546 0.49539728 0.3204722  0.01027036 0.38783377 0.05878448
 0.3064274  0.3627725  0.82904625 0.65276448 0.38172122 0.3366126
 0.95070045 0.19033623 0.65379131 0.95520339 0.24181065 0.09515548
 0.06255576 0.65637051 0.69387826 0.24728206 0.42682065 0.5071927
 0.53192884 0.24369746 0.48443777 0.35751822 0.2329893  0.56845313
 0.6931882  0.82165069 0.28444147 0.82880388 0.08243044 0.26178976
 0.51292436 0.65986697 0.2919008  0.59793908 0.60685838 0.64528586
 0.90006858 0.83552156 0.65597853 0.18574442 0.54166485 0.8986078
 0.67541775 0.93559004 0.67838876 0.68131608 0.95764807 0.65582455
 0.52360478 0.65387829 0.5244549  0.19682046 0.54796943 0.19867838
 0.71317009 0.04165085 0.23834948 0.4259043  0.53708509 0.6748215

In [ ]:
import numpy as np
array = np.zeros(10)
array[4] = 1
print (array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
arr = [1,2,0,0,4,0]
arr.reverse()
print(arr)

[0, 4, 0, 0, 2, 1]


In [ ]:
import numpy as np

def create_border_array(n):
    arr = np.zeros((n, n), dtype=int)
    arr[0, :] = 1
    arr[-1, :] = 1
    arr[:, 0] = 1
    arr[:, -1] = 1
    return arr

    n =5
    array = create_bprder_array(n)
    print(array)

In [ ]:
def create_checkerboard(size):
    if size % 2 != 0:
      raise ValueError("Size must be an even number")
      matrix = np.zeros((size , size), dtype = int)
      for i in range(size):
        for j in range(size):
          if(i + j) % 2 == 0:
            matrix[i,j] = 1
            return matrix

size = 8
checkerboard = create_checkerboard(size)
print(checkerboard)


In [ ]:
import numpy as np
x = np.array([[1,2], [3,5]])
y = np.array([[5,6], [7,8]])
sum_array = x + y
print(sum_array,"\n")

diff_array = x - y
print(diff_array,"\n")

scalar_multiple = 2 * x
print(scalar_multiple,"\n")

squared_array = x ** 2
print(squared_array,"\n")





[[ 6  8]
 [10 13]] 

[[-4 -4]
 [-4 -3]] 

[[ 2  4]
 [ 6 10]] 

[[ 1  4]
 [ 9 25]] 



In [3]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
result = np.add(x, y)
print("Addition:\n", result)
result = np.subtract(x, y)

print("Subtraction:\n", result)
result = x * 3

print("Multiplication with integer:\n", result)
result = np.square(x)

print("Square of elements:\n", result)
result = np.dot(v, w)

print("Dot product of v and w:", result)
result = np.dot(x, v)

print("Dot product of x and v:\n", result)
result = np.dot(x, y)

print("Dot product of x and y:\n", result)
result = np.concatenate((x, y), axis=0)

print("Concatenation of x and y along rows:\n", result)
result = np.vstack((v, w))

print("Concatenation of v and w along columns:\n", result)
try:
    result = np.concatenate((x, v), axis=0)
    print("Concatenation of x and v:\n", result)
except ValueError as e:
    print("Error:", e)

v_reshaped = v[np.newaxis, :]
result = np.concatenate((x, v_reshaped), axis=0)
print("Fixed concatenation:\n", result)


Addition:
 [[ 6  8]
 [10 13]]
Subtraction:
 [[-4 -4]
 [-4 -3]]
Multiplication with integer:
 [[ 3  6]
 [ 9 15]]
Square of elements:
 [[ 1  4]
 [ 9 25]]
Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]
Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Fixed concatenation:
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


In [5]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])


A_inv = np.linalg.inv(A)
result_identity = np.dot(A, A_inv)
print("A * A^-1 =\n", result_identity)

AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB =\n", AB)
print("BA =\n", BA)

AB_T = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))
print("(AB)^T =\n", AB_T)
print("B^T A^T =\n", BT_AT)


A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print("Solution X (x, y, z):", X)

det_A = np.linalg.det(A)
eigenvalues, eigenvectors = np.linalg.eig(A)
norm_A = np.linalg.norm(A)

print("Determinant of A:", det_A)
print("Eigenvalues of A:", eigenvalues)
print("Eigenvectors of A:\n", eigenvectors)
print("Norm of A:", norm_A)


A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
(AB)^T =
 [[23 51]
 [13 29]]
B^T A^T =
 [[23 51]
 [13 29]]
Solution X (x, y, z): [ 2.  1. -2.]
Determinant of A: -19.000000000000004
Eigenvalues of A: [ 1.6420583+1.75757401j  1.6420583-1.75757401j -3.2841166+0.j        ]
Eigenvectors of A:
 [[-0.382981  -0.42412518j -0.382981  +0.42412518j -0.42095922+0.j        ]
 [-0.50252881+0.17376846j -0.50252881-0.17376846j -0.48621189+0.j        ]
 [-0.62507016+0.j         -0.62507016-0.j          0.76576193+0.j        ]]
Norm of A: 5.5677643628300215


In [6]:
import numpy as np
import time

def measure_time(func, *args, **kwargs):
    start_time = time.time()
    result = func(*args, **kwargs)
    elapsed_time = time.time() - start_time
    return result, elapsed_time

#Element-wise Addition

list1 = [i for i in range(1_000_000)]
list2 = [i for i in range(1_000_000)]

def list_addition(a, b):
    return [a[i] + b[i] for i in range(len(a))]

_, time_list_add = measure_time(list_addition, list1, list2)
print(f"Element-wise addition using Python lists took: {time_list_add:.4f} seconds")

# Numpy Arrays
array1 = np.arange(1_000_000)
array2 = np.arange(1_000_000)

_, time_numpy_add = measure_time(np.add, array1, array2)
print(f"Element-wise addition using NumPy arrays took: {time_numpy_add:.4f} seconds")

#Element-wise Multiplication

def list_multiplication(a, b):
    return [a[i] * b[i] for i in range(len(a))]

_, time_list_mul = measure_time(list_multiplication, list1, list2)
print(f"Element-wise multiplication using Python lists took: {time_list_mul:.4f} seconds")

_, time_numpy_mul = measure_time(np.multiply, array1, array2)
print(f"Element-wise multiplication using NumPy arrays took: {time_numpy_mul:.4f} seconds")

#Dot Product

def list_dot_product(a, b):
    return sum(a[i] * b[i] for i in range(len(a)))

_, time_list_dot = measure_time(list_dot_product, list1, list2)
print(f"Dot product using Python lists took: {time_list_dot:.4f} seconds")

_, time_numpy_dot = measure_time(np.dot, array1, array2)
print(f"Dot product using NumPy arrays took: {time_numpy_dot:.4f} seconds")

#Matrix Multiplication

matrix1 = [[i for i in range(1000)] for _ in range(1000)]
matrix2 = [[i for i in range(1000)] for _ in range(1000)]

def list_matrix_multiplication(a, b):
    result = [[sum(a[i][k] * b[k][j] for k in range(len(b))) for j in range(len(b[0]))] for i in range(len(a))]
    return result

_, time_list_matrix_mul = measure_time(list_matrix_multiplication, matrix1, matrix2)
print(f"Matrix multiplication using Python lists took: {time_list_matrix_mul:.4f} seconds")

# Numpy Arrays
matrix1_np = np.array(matrix1)
matrix2_np = np.array(matrix2)

_, time_numpy_matrix_mul = measure_time(np.dot, matrix1_np, matrix2_np)
print(f"Matrix multiplication using NumPy arrays took: {time_numpy_matrix_mul:.4f} seconds")


Element-wise addition using Python lists took: 0.1319 seconds
Element-wise addition using NumPy arrays took: 0.0040 seconds
Element-wise multiplication using Python lists took: 0.1287 seconds
Element-wise multiplication using NumPy arrays took: 0.0039 seconds
Dot product using Python lists took: 0.1396 seconds
Dot product using NumPy arrays took: 0.0018 seconds
Matrix multiplication using Python lists took: 238.2306 seconds
Matrix multiplication using NumPy arrays took: 1.4669 seconds
